### ISSUE TITLE
Info tab on overlay can not scroll vertically

### ISSUE THREAD

**Issue by deviap-dev** [deviap/deviap-main#59]
<img width="712" alt="Screenshot 2021-02-18 at 00 50 10" src="https://user-images.githubusercontent.com/69850261/108287767-4196fa00-7183-11eb-80e2-8c7b45953bbb.png">

Expected behaviour: when vertical size of screen is limited, scrollbar should appear

**Comment by u-train** [comment]
Fixed by https://github.com/deviap/deviap-main/pull/77
